import { afterEach, describe, expect, it } from "bun:test";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { scanYarn } from "./yarn.js";

const dirs: string[] = [];
const make = async (files: Record<string, string>): Promise<string> => {
  const dir = await mkdtemp(join(tmpdir(), "sage-scan-yarn-"));
  dirs.push(dir);
  for (const [name, content] of Object.entries(files)) await writeFile(join(dir, name), content);
  return dir;
};
afterEach(async () => {
  while (dirs.length) await rm(dirs.pop()!, { recursive: true, force: true });
});

describe("scanYarn — classic (v1)", () => {
  const pkg = JSON.stringify({ dependencies: { swr: "^2.2.0", "@acme/internal": "^1.0.0" } });
  const lock = `# yarn lockfile v1


"@acme/internal@^1.0.0":
  version "1.0.0"
  resolved "https://npm.acme.local/@acme/internal/-/internal-1.0.0.tgz#h"
  integrity sha512-x

swr@^2.2.0:
  version "2.2.5"
  resolved "https://registry.yarnpkg.com/swr/-/swr-2.2.5.tgz#h"
  integrity sha512-y

dequal@^2.0.0:
  version "2.0.3"
  resolved "https://registry.npmjs.org/dequal/-/dequal-2.0.3.tgz#h"
`;

  it("reads version + classifies by the resolved URL host", async () => {
    const dir = await make({ "package.json": pkg, "yarn.lock": lock });
    const pkgs = await scanYarn(dir);
    expect(pkgs.find((p) => p.name === "swr")).toMatchObject({ version: "2.2.5", ecosystem: "npm", direct: true, publicCoordinate: true });
    expect(pkgs.find((p) => p.name === "dequal")).toMatchObject({ publicCoordinate: true, direct: false });
  });

  it("treats a custom-registry resolved URL as NOT public", async () => {
    const dir = await make({ "package.json": pkg, "yarn.lock": lock });
    expect((await scanYarn(dir)).find((p) => p.name === "@acme/internal")?.publicCoordinate).toBe(false);
  });
});

describe("scanYarn — berry (v2+)", () => {
  const pkg = JSON.stringify({ dependencies: { swr: "^2.2.0" } });
  const lock = `# This file is generated by running "yarn install"
__metadata:
  version: 8
  cacheKey: 10

"swr@npm:^2.2.0":
  version: 2.2.5
  resolution: "swr@npm:2.2.5"
  linkType: hard

"@acme/ui@workspace:packages/ui":
  version: 0.0.0-use.local
  resolution: "@acme/ui@workspace:packages/ui"
  linkType: soft

"left-pad@npm:^1.3.0":
  version: 1.3.0
  resolution: "left-pad@npm:1.3.0"
  linkType: hard
`;

  it("detects berry and classifies npm: as public", async () => {
    const dir = await make({ "package.json": pkg, "yarn.lock": lock });
    const pkgs = await scanYarn(dir);
    expect(pkgs.find((p) => p.name === "swr")).toMatchObject({ version: "2.2.5", direct: true, publicCoordinate: true });
    expect(pkgs.find((p) => p.name === "left-pad")).toMatchObject({ version: "1.3.0", publicCoordinate: true });
  });

  it("treats a workspace resolution as NOT public", async () => {
    const dir = await make({ "package.json": pkg, "yarn.lock": lock });
    expect((await scanYarn(dir)).find((p) => p.name === "@acme/ui")?.publicCoordinate).toBe(false);
  });
});
